title: BroadBanner Pages
baseurl: ""
url: "https://pages.broadbanner.com"

theme: minima

markdown: kramdown

defaults:
  - scope:
      path: "index.md"
    values:
      layout: "broad-banner"
  - scope:
      path: "sick-of-this-shit-publications"
    values:
      layout: "sick-of-this-shit-publications"
  - scope:
      path: "sick-of-this-shit-publications/intelligent-masculinity"
    values:
      layout: "intelligent-masculinity"
  - scope:
      path: "banner-and-backbone-media"
    values:
      layout: "banner-and-backbone-media"
  - scope:
      path: "banner-and-backbone-media/anti-fascist-book-club"
    values:
      layout: "anti-fascist-book-club"
  - scope:
      path: "banner-and-backbone-media/palantalk"
    values:
      layout: "palantalk"
  - scope:
      path: "firebrand-project"
    values:
      layout: "firebrand-project"
  - scope:
      path: "this-woman-votes"
    values:
      layout: "this-woman-votes"
  - scope:
      path: "this-woman-votes/epistemic-warfare"
    values:
      layout: "this-woman-votes--epistemic-warfare"
